# defaults/main.yml

# Installation Directory
alertmanager_install_dir: /opt/alertmanager

# Ownership and Permissions
alertmanager_owner: ansible
alertmanager_group: ansible
alertmanager_directory_mode: '0755'
docker_compose_file_mode: '0644'

# Docker Compose Configuration
alertmanager_container_name: alertmanager
alertmanager_image: prom/alertmanager
alertmanager_image_tag: v0.27.0
alertmanager_ports:
  - "9093:9093"
alertmanager_restart_policy: always
alertmanager_networks:
  - monitoring
alertmanager_labels:
  prometheus_job: "alertmanager"
  prometheus_port: "9093"

# Docker Networks
alertmanager_network_definitions:
  monitoring:
    external: true
