grafana_install_dir: /opt/grafana
grafana_dashboards_dir: "{{ grafana_install_dir }}/provisioning/dashboards"
grafana_datasources_dir: "{{ grafana_install_dir }}/provisioning/datasources"
grafana_docker_compose_file: "{{ grafana_install_dir }}/docker-compose.yml"
grafana_container_name: grafana
grafana_admin_password: 2451919
prometheus_url: http://prometheus:9090
