
- name: Ensure /opt/node_exporter directory exists
  file:
    path: "/opt/node_exporter"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Docker-compose for Prometheus
  template:
    src: "docker-compose.yml.j2"
    dest: "/opt/node_exporter/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'

- name: Deploy (start) node_exporter with docker-compose
  community.docker.docker_compose_v2:
    project_src: "/opt/node_exporter"
    state: present

