---
- name: Ensure required Grafana directories exist on the server
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ grafana_install_dir }}"
    - "{{ grafana_dashboards_dir }}"
    - "{{ grafana_datasources_dir }}"
  loop_control:
    label: "{{ item }}"

- name: Copy dashboard and provisioner
  copy:
    src: dashboards/
    dest: "{{ grafana_dashboards_dir }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Grafana

- name: Copy datasources JSON
  copy:
    src: datasources.yml
    dest: "{{ grafana_datasources_dir }}/datasource-prometheus.yml"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Grafana

- name: Deploy Docker Compose file for Grafana
  template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_docker_compose_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Grafana

- name: Deploy (start) Grafana with docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_install_dir }}"
    state: present
