- hosts: lido
  remote_user: root
  roles:
    # - ansible-role-create-users
    # - ansible-role-docker

- hosts: lido
  remote_user: ansible
  roles:
    - prometheus
    # - loki
    # - grafana
    # - node_exporter
    # - cadvisor
    # - alertmanager

# - import_playbook: result.yml

