- hosts: lido
  remote_user: root
  roles:
    - ansible-role-create-users
    - ansible-role-docker

- hosts: lido
  remote_user: ansible
  roles:
    - prometheus
    - grafana
    - node_exporter
    - alertmanager
    - cadvisor
    - loki