- hosts: lido
  recome_user: root
  roles:
#    - ansible-role-create-users
    # - ansible-role-docker

- hosts: lido
  recome_user: ansible
  roles:
#    - prometheus
     - grafana
#     - node_exporter
#     - alertmanager
#     - cadvisor
#     - loki