# tasks/main.yml

- name: Ensure Prometheus installation directory exists
  file:
    path: "{{ prometheus_install_dir }}"
    state: directory
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    mode: "{{ prometheus_directory_mode }}"
  become: yes

- name: Copy Prometheus configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ prometheus_install_dir }}/{{ item.dest }}"
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    mode: "{{ prometheus_file_mode }}"
  loop:
    - { src: "prometheus_config/prometheus.yml", dest: "prometheus.yml" }
    - { src: "prometheus_config/monitoring.rules.yml", dest: "monitoring.rules.yml" }
    - { src: "prometheus_config/alerts.rules.yml", dest: "alerts.rules.yml" }
    - { src: "prometheus_config/tests.yml", dest: "tests.yml" }
  notify: Restart Prometheus

- name: Copy Docker Compose file for Prometheus
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ prometheus_install_dir }}/docker-compose.yml"
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    mode: "{{ prometheus_file_mode }}"
  notify: Restart Prometheus

- name: Deploy (start) Prometheus with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_install_dir }}"
    state: present
