---
# handlers/restart_grafana.yml

    - name: Restart grafana container
      community.docker.docker_compose_v2:
        project_src: "{{ grafana_install_dir }}"
        state: restarted

    - name: Wait for a few seconds before fetching container information
      ansible.builtin.pause:
        seconds: 5

    - name: Get information on grafana container
      community.docker.docker_container_info:
        name: "{{ grafana_container_name }}"
      register: container_info

    - name: Notify if container does not exist
      ansible.builtin.fail:
        msg: "grafana container '{{ grafana_container_name }}' does not exist. Please check deployment."
      when: not container_info.exists

    - name: Notify if container is not running
      ansible.builtin.fail:
        msg: "grafana container '{{ grafana_container_name }}' is not running. Please check configuration."
      when: container_info.exists and container_info.container.State.Status != "running"

    - name: Print grafana container status
      ansible.builtin.debug:
        msg: "grafana container '{{ grafana_container_name }}' is running."
      when: container_info.exists and container_info.container.State.Status == "running"