---
- name: Ensure required Loki directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: ansible
    group: ansible
    mode: '0755'
  loop:
    - "{{ loki_install_dir }}"
    - "{{ loki_config_dir }}"
    - "{{ loki_data_dir }}"
  loop_control:
    label: "{{ item }}"
  become: yes

- name: Copy Loki configuration
  copy:
    src: loki-config.yml
    dest: "{{ loki_config_dir }}/loki-config.yml"
    owner: ansible
    group: ansible
    mode: '0644'
  notify: Restart Loki


- name: Deploy Docker Compose file for Loki
  template:
    src: docker-compose.yml.j2
    dest: "{{ loki_install_dir }}/docker-compose.yml"
    owner: ansible
    group: ansible
    mode: '0644'
  notify: Restart Loki

- name: Start Loki with docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ loki_install_dir }}"
    state: present

# - name: Install grafana/loki-docker-driver plugin
#   community.docker.docker_plugin:
#     plugin_name: grafana/loki-docker-driver:2.9.2
#     alias: loki
#     state: present
#   become: yes

# - name: Ensure /etc/docker/ directory exists.
#   file:
#     path: /etc/docker
#     state: directory
#     mode: 0755
#   when: docker_daemon_options.keys() | length > 0
#   become: yes

# - name: Configure Docker daemon options.
#   copy:
#     content: "{{ docker_daemon_options | to_nice_json }}"
#     dest: /etc/docker/daemon.json
#     mode: 0644
#   when: docker_daemon_options.keys() | length > 0
#   notify: restart docker
#   become: yes
